### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by nuts3745** [ics-creative/180302_electron_tutorial#1]
### 問題の内容
`Uncaught ReferenceError: process is not defined`
というエラーでスクリプトが動作しない。

### 実行環境
- macOS 10.14.6
- node 10.15.1
- electron 6.4.1

### 期待する動作
`process`が動作すること。

### 修正したこと
`main.js`で`nodeIntegration`をオンにしたら動作した。

```main.js
mainWindow = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true
        },
        width: 800,
        height: 600
    });
```

**Comment by ics-ikeda** [comment]
ご指摘頂きましてありがとうございます。
ご提案いただいた方法で動作することを確認しましたので、サンプルと記事の内容を修正いたしました。
